-- Migration: 006_seed_new_features.sql
-- Seed data for new EnglishMitraAI features

-- ─── DAILY GREETINGS ──────────────────────────────────────────────────────
INSERT INTO daily_greetings (date, category, greeting_english, greeting_telugu, pronunciation_guide, usage_examples, cultural_note, difficulty) VALUES
(CURRENT_DATE,       'morning',      'Good morning! How are you today?',                   'శుభోదయం! మీరు ఎలా ఉన్నారు?',                             '/gʊd ˈmɔːrnɪŋ haʊ ɑːr juː/',          '["When arriving at office", "Meeting neighbors in the morning", "Starting a phone call"]'::jsonb,      'Always smile when greeting in professional settings. Eye contact is appreciated.',             1),
(CURRENT_DATE + 1,   'professional', 'Good morning, sir. How may I assist you?',           'శుభోదయం, సార్. నేను మీకు ఎలా సహాయపడగలను?',               '/gʊd ˈmɔːrnɪŋ sɜːr haʊ meɪ aɪ əˈsɪst juː/', '["When a customer enters your shop", "At office reception", "Phone reception greeting"]'::jsonb, 'Use sir/ma''am in formal Indian work contexts. It shows respect.',                              2),
(CURRENT_DATE + 2,   'casual',       'Hey! What''s up? Long time no see!',                 'హే! ఏం జరుగుతోంది? చాలా కాలం అయింది!',                   '/heɪ wɒts ʌp lɒŋ taɪm nəʊ siː/',     '["Meeting a friend after long time", "Casual office chat", "Social media message"]'::jsonb,           'Use ONLY with close friends or peers. Never with seniors or strangers.',                       1),
(CURRENT_DATE + 3,   'evening',      'Good evening! Hope you had a wonderful day!',        'శుభ సాయంత్రం! మీకు చాలా మంచి రోజు గడిచిందని ఆశిస్తున్నాను!', '/gʊd ˈiːvnɪŋ həʊp juː hæd ə ˈwʌndəfəl deɪ/', '["After work hours greeting", "Evening social events", "Dinner meetings"]'::jsonb,         'Use after 5 PM. Shows warmth and care about the other person''s day.',                         1),
(CURRENT_DATE + 4,   'professional', 'Welcome! Please come in. How can I help you today?', 'స్వాగతం! దయచేసి లోపలికి రండి. నేడు నేను మీకు ఎలా సహాయపడగలను?', '/ˈwelkəm pliːz kʌm ɪn haʊ kæn aɪ help juː/', '["Shop or store entry", "Office reception", "Bank or hospital greeting"]'::jsonb,         'Smile and make eye contact. Stand up to greet VIP customers.',                                2),
(CURRENT_DATE + 5,   'festival',     'Happy Diwali! May this festival bring you joy and prosperity!', 'దీపావళి శుభాకాంక్షలు! ఈ పండుగ మీకు ఆనందాన్ని మరియు సంపదను తీసుకొస్తుందని ఆశిస్తున్నాను!', '/ˈhæpi dɪˈwɑːli meɪ ðɪs ˈfestɪvəl brɪŋ juː dʒɔɪ/', '["Festival season greetings", "WhatsApp messages to clients", "Office Diwali celebration"]'::jsonb, 'Festival greetings strengthen professional relationships in Indian culture.',                  2),
(CURRENT_DATE + 6,   'casual',       'Dude! You look amazing! What''s your secret?',       'యార్! నువ్వు అద్భుతంగా కనిపిస్తున్నావు! నీ రహస్యం ఏంటి?', '/djuːd juː lʊk əˈmeɪzɪŋ wɒts jɔːr ˈsiːkrɪt/', '["Meeting friends at parties", "Complimenting a colleague''s new look", "Social gatherings"]'::jsonb, 'Very casual — use only with close friends. Great for building rapport.',                      1)
ON CONFLICT (date) DO NOTHING;

-- ─── SELF INTRODUCTION TEMPLATES ─────────────────────────────────────────
INSERT INTO self_introduction_templates (level, title, template_english, template_telugu, key_phrases, tips) VALUES
('student',
 'Student Self Introduction',
 'Hi, I am [Your Name]. I am currently studying [Course Name] at [College Name] in [City]. I am in my [Year] year. I am interested in [Subject/Field] and I enjoy [Hobby]. In the future, I want to become a [Career Goal]. I am excited to be here and looking forward to learning from all of you.',
 'హాయ్, నా పేరు [మీ పేరు]. నేను ప్రస్తుతం [నగరం]లోని [కళాశాల పేరు]లో [కోర్సు పేరు] చదువుతున్నాను. నేను [విభాగం/రంగం]లో ఆసక్తి కలిగి ఉన్నాను.',
 '[{"english": "I am currently studying", "telugu": "నేను ప్రస్తుతం చదువుతున్నాను"}, {"english": "I am interested in", "telugu": "నాకు ఆసక్తి ఉంది"}, {"english": "In the future, I want to become", "telugu": "భవిష్యత్తులో నేను అవ్వాలనుకుంటున్నాను"}]'::jsonb,
 '["Speak slowly and clearly", "Make eye contact with the audience", "Smile when you introduce yourself", "Practice 3-4 times before the actual introduction", "Keep it under 60 seconds"]'::jsonb),

('fresher',
 'Fresher Job Interview Introduction',
 'Good morning, sir/ma''am. My name is [Your Name]. I have recently completed my [Degree] in [Specialization] from [College Name] with [Percentage/CGPA]. During my studies, I worked on [Project Name], which helped me develop skills in [Skill 1] and [Skill 2]. I am a quick learner, hardworking, and eager to contribute to your organization. I am very excited about this opportunity and confident that I can add value to your team.',
 'శుభోదయం, సార్/మేడమ్. నా పేరు [మీ పేరు]. నేను ఇటీవల [కళాశాల పేరు] నుండి [స్పెషలైజేషన్]లో [డిగ్రీ] పూర్తి చేశాను.',
 '[{"english": "I have recently completed", "telugu": "నేను ఇటీవల పూర్తి చేశాను"}, {"english": "I am a quick learner", "telugu": "నేను త్వరగా నేర్చుకుంటాను"}, {"english": "eager to contribute", "telugu": "సహాయపడటానికి సిద్ధంగా ఉన్నాను"}, {"english": "add value to your team", "telugu": "మీ టీమ్‌కు విలువను జోడించడానికి"}]'::jsonb,
 '["Mention your CGPA only if above 7.0", "Highlight your final year project", "Show enthusiasm for the company", "Research the company before the interview", "Dress professionally and sit straight"]'::jsonb),

('experienced',
 'Experienced Professional Introduction',
 'Good morning. My name is [Your Name], and I have [X] years of experience in [Industry/Domain]. Currently, I am working as a [Job Title] at [Company Name], where I am responsible for [Key Responsibility]. In my career, I have successfully [Achievement 1] and [Achievement 2]. I specialize in [Core Skill] and have strong expertise in [Technical Skill]. I am looking for an opportunity to grow further and contribute my skills to [Target Company].',
 'శుభోదయం. నా పేరు [మీ పేరు], నాకు [పరిశ్రమ/డొమైన్]లో [X] సంవత్సరాల అనుభవం ఉంది. ప్రస్తుతం నేను [కంపెనీ పేరు]లో [జాబ్ టైటిల్]గా పని చేస్తున్నాను.',
 '[{"english": "I have X years of experience", "telugu": "నాకు X సంవత్సరాల అనుభవం ఉంది"}, {"english": "I am responsible for", "telugu": "నేను బాధ్యత వహిస్తున్నాను"}, {"english": "I specialize in", "telugu": "నేను దీనిలో నిపుణుడిని"}, {"english": "looking for an opportunity", "telugu": "అవకాశం కోసం చూస్తున్నాను"}]'::jsonb,
 '["Lead with your years of experience", "Mention 1-2 key achievements with numbers", "Show growth mindset", "Connect your experience to the new role", "Keep it under 2 minutes"]'::jsonb),

('interview',
 'Interview Self Introduction (HR Round)',
 'Good morning, sir/ma''am. Thank you for giving me this opportunity. My name is [Full Name]. I am from [City], [State]. I completed my [Degree] from [University] in [Year]. I have [X years] of experience in [Domain]. In my current role at [Company], I [Key Achievement]. My key strengths are [Strength 1], [Strength 2], and [Strength 3]. I am passionate about [Field] and I believe my skills and experience make me a strong fit for this position. I am looking forward to being part of your team.',
 'శుభోదయం, సార్/మేడమ్. నాకు ఈ అవకాశం ఇచ్చినందుకు ధన్యవాదాలు. నా పేరు [పూర్తి పేరు]. నేను [రాష్ట్రం], [నగరం] నుండి వచ్చాను.',
 '[{"english": "Thank you for giving me this opportunity", "telugu": "నాకు ఈ అవకాశం ఇచ్చినందుకు ధన్యవాదాలు"}, {"english": "I am a strong fit for this position", "telugu": "నేను ఈ పదవికి సరైన వ్యక్తిని"}, {"english": "looking forward to being part of", "telugu": "భాగమవ్వాలని ఎదురుచూస్తున్నాను"}]'::jsonb,
 '["Start with a confident greeting", "Thank them for the opportunity", "Keep it 1.5-2 minutes", "End with enthusiasm about joining", "Practice until it sounds natural, not memorized"]'::jsonb),

('public_speaking',
 'Public Speaking Introduction',
 'Good evening, ladies and gentlemen. It is a great honor and privilege to stand before you today. My name is [Your Name], and I am here to speak about [Topic]. Over the past [X years], I have had the opportunity to [Relevant Experience]. Today, I would like to share with you [Key Message]. I hope my words will inspire you and give you a fresh perspective on [Topic]. Thank you for being here.',
 'శుభ సాయంత్రం, మహిళలు మరియు పెద్దమనుషులు. ఈ రోజు మీ ముందు నిలబడటం నాకు గొప్ప గౌరవంగా భావిస్తున్నాను.',
 '[{"english": "It is a great honor and privilege", "telugu": "ఇది నాకు గొప్ప గౌరవం"}, {"english": "I would like to share with you", "telugu": "నేను మీతో పంచుకోవాలనుకుంటున్నాను"}, {"english": "I hope my words will inspire you", "telugu": "నా మాటలు మిమ్మల్ని స్ఫూర్తింప జేస్తాయని ఆశిస్తున్నాను"}]'::jsonb,
 '["Use a powerful opening hook", "Speak slower than you think you need to", "Use pauses for emphasis", "Make eye contact with different sections", "Project your voice to the back of the room"]'::jsonb),

('networking',
 'Business Networking Introduction',
 'Hi! I''m [Your Name]. I work as a [Job Title] at [Company Name]. We help [Target Customer] to [Value Proposition]. What do you do? I''d love to learn more about your work. Here''s my card — do you have yours? It was great meeting you! Let''s connect on LinkedIn.',
 'హాయ్! నా పేరు [మీ పేరు]. నేను [కంపెనీ పేరు]లో [జాబ్ టైటిల్]గా పని చేస్తున్నాను. మీరు ఏమి చేస్తారు? మీ పని గురించి మరింత తెలుసుకోవాలనుకుంటున్నాను.',
 '[{"english": "We help [customer] to [value]", "telugu": "మేము [కస్టమర్]కు [విలువ] అందిస్తాము"}, {"english": "I''d love to learn more about", "telugu": "గురించి మరింత తెలుసుకోవాలనుకుంటున్నాను"}, {"english": "Let''s connect on LinkedIn", "telugu": "లింక్డ్‌ఇన్‌లో కనెక్ట్ అవుదాం"}]'::jsonb,
 '["Keep it under 30 seconds", "Focus on the other person — ask questions", "Have your business card ready", "Follow up within 24 hours", "Find a common interest to build rapport"]'::jsonb)
ON CONFLICT DO NOTHING;

-- ─── OFFICE SCENARIOS ─────────────────────────────────────────────────────
INSERT INTO office_scenarios (title, title_telugu, category, difficulty, ai_persona, system_prompt, starter_message, key_vocabulary, cultural_tips) VALUES
('Requesting Leave from Manager',
 'మేనేజర్ నుండి సెలవు అడగడం',
 'leave_request', 2,
 'Ravi Sharma (Your Manager)',
 'You are Ravi Sharma, a professional Indian IT manager. The user wants to request leave. Be professional but approachable. Ask for reason, dates, and whether work will be covered. Respond naturally as a manager would. Correct the user''s English gently if needed.',
 'Good morning! You look like you have something to discuss. Please come in and sit down. What''s on your mind?',
 '[{"word": "request leave", "meaning": "సెలవు కోసం అడగడం", "example": "I would like to request leave for two days."}, {"word": "prior commitments", "meaning": "ముందే నిర్ణయించిన పని", "example": "I have prior commitments on that day."}, {"word": "cover my work", "meaning": "నా పని చూసుకోవడం", "example": "I will ensure my colleague covers my work."}, {"word": "approval", "meaning": "అనుమతి", "example": "Kindly grant me your approval."}]'::jsonb,
 'In Indian offices, always give advance notice for leave. Mention who will cover your work. Use formal language with managers.'),

('Daily Standup Meeting',
 'రోజువారీ స్టాండప్ మీటింగ్',
 'daily_standup', 1,
 'Scrum Master Deepa',
 'You are Deepa, a scrum master running a daily standup. Ask the user: what did you do yesterday, what are you doing today, any blockers? Keep it brisk and professional. Encourage clear communication.',
 'Good morning team! Let''s start our daily standup. [Name], let''s begin with you. What did you work on yesterday?',
 '[{"word": "blocker", "meaning": "ఆటంకం", "example": "I have a blocker — the API is not working."}, {"word": "in progress", "meaning": "పని జరుగుతోంది", "example": "The login feature is in progress."}, {"word": "completed", "meaning": "పూర్తయింది", "example": "I completed the database migration yesterday."}, {"word": "pull request", "meaning": "కోడ్ రివ్యూ అభ్యర్థన", "example": "I raised a pull request for the new feature."}]'::jsonb,
 'Standups are typically 15 minutes max. Be concise. Mention only blockers, not solutions. Solutions are discussed after the meeting.'),

('Client Call - Project Update',
 'క్లయింట్ కాల్ - ప్రాజెక్ట్ అప్‌డేట్',
 'client_call', 4,
 'Mr. Anderson (US Client)',
 'You are Mr. Anderson, a professional American client. The user is giving you a project status update. Ask questions about timelines, risks, and deliverables. Be professional, slightly formal. Expect clear and confident communication.',
 'Hi! Thanks for joining the call. I hope it''s a good time for you. I''d like to start with a quick status update on the project. Can you walk me through where things stand?',
 '[{"word": "deliverables", "meaning": "అందించాల్సిన వస్తువులు/ఫలితాలు", "example": "All deliverables for Sprint 3 are on track."}, {"word": "milestone", "meaning": "ముఖ్యమైన దశ", "example": "We have reached the first milestone."}, {"word": "bandwidth", "meaning": "సమయం/సామర్థ్యం", "example": "We don''t have the bandwidth for extra features this sprint."}, {"word": "risk", "meaning": "ప్రమాదం/నష్టం", "example": "There is a risk of delay due to the API dependency."}]'::jsonb,
 'With US/UK clients, be direct and concise. Lead with status, then details. Quantify progress with percentages. Always have a clear next step.'),

('HR Salary Discussion',
 'HR జీతం చర్చ',
 'hr_communication', 3,
 'Priya (HR Manager)',
 'You are Priya, an HR manager in an Indian IT company. The user wants to discuss salary hike or CTC negotiation. Be professional, listen carefully, and respond as HR would — with company policy constraints but a genuine desire to retain good employees.',
 'Hi, please have a seat. I understand you wanted to discuss your compensation. I''m happy to have this conversation. Tell me, what''s on your mind?',
 '[{"word": "CTC", "meaning": "వేతన ప్యాకేజ్", "example": "My expected CTC is 8 LPA."}, {"word": "hike", "meaning": "జీతం పెంపు", "example": "I am expecting a 20% hike this year."}, {"word": "appraisal", "meaning": "పనితీరు మూల్యాంకనం", "example": "My appraisal rating was Exceeds Expectations."}, {"word": "negotiate", "meaning": "చర్చించడం", "example": "I would like to negotiate the offer."}]'::jsonb,
 'Always come with data — your achievements, market rate research. Be confident but respectful. Never give ultimatums in the first meeting.'),

('Team Meeting Participation',
 'టీమ్ మీటింగ్‌లో పాల్గొనడం',
 'team_meeting', 2,
 'Team Lead Suresh',
 'You are Suresh, a friendly team lead running a project planning meeting. Involve the user by asking their opinion on sprint planning, task distribution, and timelines. Encourage participation.',
 'Alright team, let''s get started. We have a new feature to plan for next sprint. I want everyone''s input. [Name], you''ve worked on similar features before — what''s your initial estimate?',
 '[{"word": "estimate", "meaning": "అంచనా", "example": "My estimate for this task is 3 days."}, {"word": "dependencies", "meaning": "ఆధారపడే పనులు", "example": "This task has dependencies on the backend API."}, {"word": "assign", "meaning": "అప్పగించడం", "example": "Can we assign this to the frontend team?"}, {"word": "sprint goal", "meaning": "స్ప్రింట్ లక్ష్యం", "example": "Our sprint goal is to complete the user module."}]'::jsonb,
 'Speak up in meetings — silence is often interpreted as agreement or lack of engagement. Prepare your points before the meeting.'),

('Remote Work Communication',
 'రిమోట్ వర్క్ కమ్యూనికేషన్',
 'remote_work', 2,
 'Manager Kavitha (on video call)',
 'You are Kavitha, a manager checking in with a remote employee. Ask about their work setup, productivity, any issues with connectivity, and whether they need any support. Be supportive and understanding.',
 'Hi! Good to see you on the video call. How are things working out from home? Are you comfortable with the setup?',
 '[{"word": "working from home", "meaning": "ఇంటి నుండి పని చేయడం", "example": "I have been working from home for 2 years now."}, {"word": "connectivity issue", "meaning": "ఇంటర్నెట్ సమస్య", "example": "I had a connectivity issue this morning."}, {"word": "productive", "meaning": "ఉత్పాదకంగా", "example": "I feel more productive working from home."}, {"word": "collaboration tool", "meaning": "సహకార సాధనం", "example": "We use Slack and Zoom as collaboration tools."}]'::jsonb,
 'Over-communicate in remote work. Send status updates proactively. Keep your camera on during meetings. Respond to messages within 30 minutes during work hours.'),

('Professional Small Talk',
 'ప్రొఫెషనల్ స్మాల్ టాక్',
 'small_talk', 1,
 'Colleague Arjun (Office Kitchen)',
 'You are Arjun, a friendly colleague. Chat casually about weekend plans, recent news, cricket, movies, or work-life topics. Keep it light and fun. Help the user practice casual English.',
 'Hey! Getting your morning coffee too? What a week it''s been, right? Did you watch the IPL match last night?',
 '[{"word": "catch up", "meaning": "మళ్ళీ మాట్లాడడం", "example": "Let''s catch up over lunch sometime."}, {"word": "hectic", "meaning": "చాలా బిజీగా", "example": "This week has been really hectic."}, {"word": "unwind", "meaning": "రిలాక్స్ అవ్వడం", "example": "I like to unwind by watching movies on weekends."}, {"word": "hang out", "meaning": "కలిసి టైమ్ గడపడం", "example": "We should hang out this weekend."}]'::jsonb,
 'Small talk builds relationships at work. Topics: cricket, movies, food, traffic, weather, weekend plans. Avoid: salary, politics, religion.'),

('Project Discussion with Developer',
 'డెవలపర్‌తో ప్రాజెక్ట్ చర్చ',
 'project_discussion', 3,
 'Senior Developer Vikram',
 'You are Vikram, a senior developer. Discuss technical requirements, architecture decisions, or code review feedback. Use technical terms but explain them if needed. Be collaborative.',
 'Hey, good timing. I was just reviewing your code. I had a few thoughts — want to walk through it together? I think we can optimize the database queries.',
 '[{"word": "refactor", "meaning": "కోడ్ మెరుగుపరచడం", "example": "We need to refactor this function for better performance."}, {"word": "optimize", "meaning": "మెరుగుపరచడం", "example": "Let''s optimize the database query."}, {"word": "code review", "meaning": "కోడ్ పరిశీలన", "example": "Your code review comments were very helpful."}, {"word": "scalable", "meaning": "విస్తరించగలిగేది", "example": "We need a scalable architecture for this feature."}]'::jsonb,
 'In technical discussions, it''s okay to say "Let me think about that" or "Can you clarify?". Admitting you don''t know something is professional, not weak.'),

('Work Status Update to Manager',
 'మేనేజర్‌కు పని స్టేటస్ అప్‌డేట్',
 'work_update', 2,
 'Manager Anitha',
 'You are Anitha, a manager asking for a work update. Ask about task progress, any roadblocks, and next steps. Be professional but supportive.',
 'Hi! I wanted to touch base with you about the dashboard project. How is it coming along? Are you on track for the Friday deadline?',
 '[{"word": "on track", "meaning": "సరైన దారిలో ఉంది", "example": "The project is on track for the deadline."}, {"word": "roadblock", "meaning": "ఆటంకం", "example": "I hit a roadblock with the third-party API."}, {"word": "ahead of schedule", "meaning": "నిర్ణీత సమయానికి ముందే", "example": "We are ahead of schedule on this feature."}, {"word": "wrap up", "meaning": "పూర్తి చేయడం", "example": "I will wrap up the testing by tomorrow."}]'::jsonb,
 'Always lead with the good news, then mention issues. Have solutions ready when presenting problems to managers.'),

('HR Interview Round',
 'HR ఇంటర్వ్యూ రౌండ్',
 'hr_communication', 3,
 'HR Recruiter Sneha',
 'You are Sneha, an HR recruiter conducting a telephonic/in-person HR screening. Ask standard HR questions about experience, salary expectations, notice period, and career goals. Be friendly but professional.',
 'Hi [Name], welcome! Thank you for coming in today. Please make yourself comfortable. I''ve had a chance to look at your resume — it''s quite impressive. Shall we start? Can you begin by telling me a little about yourself?',
 '[{"word": "notice period", "meaning": "నోటీస్ పీరియడ్", "example": "My notice period is 30 days."}, {"word": "career goals", "meaning": "కెరీర్ లక్ష్యాలు", "example": "My career goal is to become a tech lead in 3 years."}, {"word": "compensation", "meaning": "వేతనం", "example": "My expected compensation is 12 LPA."}, {"word": "joining date", "meaning": "చేరే తేదీ", "example": "I can join within 45 days."}]'::jsonb,
 'HR rounds test communication skills as much as qualifications. Be confident, honest, and enthusiastic. Research the company salary range beforehand.')
ON CONFLICT DO NOTHING;

-- ─── EMAIL TEMPLATES ──────────────────────────────────────────────────────
INSERT INTO email_templates (category, subject, body, body_telugu, formality_level, key_phrases, mistakes_to_avoid) VALUES
('leave_request',
 'Leave Request for [Start Date] to [End Date]',
 E'Dear [Manager''s Name],\n\nI am writing to formally request leave from [Start Date] to [End Date] for [Reason — e.g., personal reasons / family function / health issues].\n\nI will ensure all my pending tasks are completed before I go on leave. I have also coordinated with [Colleague Name] to handle any urgent matters in my absence.\n\nI kindly request you to grant my leave application at your earliest convenience.\n\nThank you for your understanding and support.\n\nBest regards,\n[Your Name]\n[Designation] | [Department]',
 E'ప్రియమైన [మేనేజర్ పేరు],\n\nనేను [ప్రారంభ తేదీ] నుండి [ముగింపు తేదీ] వరకు [కారణం] కోసం సెలవు కోసం అభ్యర్థిస్తున్నాను.\n\nనేను వెళ్ళే ముందు నా పెండింగ్ టాస్క్‌లన్నీ పూర్తి చేస్తాను.',
 'formal',
 '["I am writing to formally request", "I kindly request you to grant", "handle any urgent matters in my absence", "at your earliest convenience"]'::jsonb,
 '["Don''t write ''I want leave'' — say ''I would like to request leave''", "Don''t forget to mention who will cover your work", "Don''t use casual language like ''hey'' or ''ASAP''"]'::jsonb),

('job_application',
 'Application for [Job Title] Position — [Your Name]',
 E'Dear Hiring Manager,\n\nI am writing to express my interest in the [Job Title] position at [Company Name], as advertised on [Job Portal / LinkedIn / Company Website].\n\nWith [X years] of experience in [Domain/Field], I have developed strong expertise in [Skill 1], [Skill 2], and [Skill 3]. In my current role at [Current Company], I successfully [Key Achievement — e.g., reduced load time by 40% / led a team of 5 developers].\n\nI am particularly excited about [Company Name] because of [Specific Reason — company mission, products, culture]. I am confident that my background and enthusiasm make me an excellent candidate for this role.\n\nI have attached my resume for your review. I would welcome the opportunity to discuss how my experience aligns with your requirements.\n\nThank you for your time and consideration.\n\nSincerely,\n[Your Full Name]\n[Phone Number] | [Email] | [LinkedIn URL]',
 E'ప్రియమైన నియామక నిర్వాహకుడు,\n\n[కంపెనీ పేరు]లో [జాబ్ టైటిల్] పదవికి నా ఆసక్తిని వ్యక్తం చేయడానికి రాస్తున్నాను.',
 'formal',
 '["I am writing to express my interest in", "I have developed strong expertise in", "I am particularly excited about", "I would welcome the opportunity to discuss"]'::jsonb,
 '["Don''t start with ''I am [Name]''", "Don''t copy-paste generic cover letters", "Don''t forget to tailor it to the specific company", "Always mention a specific achievement with numbers"]'::jsonb),

('interview_thankyou',
 'Thank You for the Interview — [Your Name]',
 E'Dear [Interviewer''s Name],\n\nThank you so much for taking the time to interview me for the [Job Title] position at [Company Name] today. I genuinely enjoyed our conversation, especially the discussion about [Specific Topic from Interview].\n\nOur conversation reinforced my enthusiasm for this role and my confidence that I can contribute meaningfully to [Team/Company]. I am particularly excited about [Specific Aspect of the Role/Company].\n\nPlease let me know if you need any additional information from my side. I look forward to hearing from you regarding the next steps.\n\nThank you again for this wonderful opportunity.\n\nWarm regards,\n[Your Name]\n[Phone Number]',
 E'ప్రియమైన [ఇంటర్వ్యూయర్ పేరు],\n\nఈరోజు [కంపెనీ పేరు]లో [జాబ్ టైటిల్] పదవికి నాకు ఇంటర్వ్యూ చేసినందుకు చాలా ధన్యవాదాలు.',
 'formal',
 '["Thank you for taking the time", "Our conversation reinforced my enthusiasm", "I look forward to hearing from you", "regarding the next steps"]'::jsonb,
 '["Send within 24 hours of the interview", "Don''t ask about salary in the thank you email", "Reference something specific from the interview", "Don''t be overly casual"]'::jsonb),

('meeting_request',
 'Meeting Request: [Topic] — [Date/Time Suggestion]',
 E'Dear [Name],\n\nI hope you are doing well. I would like to schedule a meeting with you to discuss [Topic/Purpose]. This will take approximately [Duration — e.g., 30 minutes].\n\nCould you please let me know your availability for any of the following time slots?\n\n- [Option 1: e.g., Monday, [Date] at 10:00 AM]\n- [Option 2: e.g., Tuesday, [Date] at 2:00 PM]\n- [Option 3: e.g., Wednesday, [Date] at 11:00 AM]\n\nIf none of these work for you, please suggest a time that is convenient, and I will do my best to accommodate.\n\nThank you for your time.\n\nBest regards,\n[Your Name]',
 E'ప్రియమైన [పేరు],\n\nమీకు బాగున్నారని ఆశిస్తున్నాను. [విషయం] గురించి చర్చించడానికి మీతో సమావేశం షెడ్యూల్ చేయాలనుకుంటున్నాను.',
 'semi_formal',
 '["I would like to schedule a meeting", "let me know your availability", "I will do my best to accommodate", "at your earliest convenience"]'::jsonb,
 '["Don''t say ''free time'' — say ''availability''", "Always offer multiple time options", "Mention the purpose and duration clearly", "Don''t forget to include your time zone for cross-location meetings"]'::jsonb),

('followup',
 'Following Up on [Previous Email/Application/Meeting] — [Your Name]',
 E'Dear [Name],\n\nI hope this email finds you well. I am writing to follow up on my [email/application/proposal] regarding [Topic], which I sent on [Date].\n\nI understand you may be busy, and I do not want to be an inconvenience. However, I would appreciate any update or feedback at your earliest convenience.\n\nIf you require any additional information from my side, please do not hesitate to reach out. I am happy to provide any clarifications.\n\nThank you for your time, and I look forward to your response.\n\nBest regards,\n[Your Name]',
 E'ప్రియమైన [పేరు],\n\nమీరు బాగున్నారని ఆశిస్తున్నాను. [తేదీ]న నేను పంపిన [విషయం] గురించి నేను ఫాలో అప్ చేయడానికి రాస్తున్నాను.',
 'semi_formal',
 '["I am writing to follow up on", "I understand you may be busy", "at your earliest convenience", "please do not hesitate to reach out"]'::jsonb,
 '["Don''t sound demanding or impatient", "Wait at least 3-5 business days before following up", "Reference the original email/date", "Don''t send more than 2 follow-up emails"]'::jsonb),

('apology',
 'Apology for [Issue/Mistake] — [Your Name]',
 E'Dear [Name],\n\nI sincerely apologize for [Specific Issue — e.g., the delay in submitting the report / the miscommunication / the error in the data].\n\nI understand that this may have caused inconvenience, and I take full responsibility for this oversight. The issue occurred due to [Brief Honest Reason], and I have taken immediate steps to [How You Fixed It / Will Prevent It].\n\nI assure you that this will not happen again. Please let me know if there is anything else I can do to resolve this situation.\n\nOnce again, I am truly sorry for any inconvenience this may have caused.\n\nSincerely,\n[Your Name]',
 E'ప్రియమైన [పేరు],\n\n[నిర్దిష్ట సమస్య] కోసం నేను హృదయపూర్వకంగా క్షమాపణ చేస్తున్నాను.',
 'formal',
 '["I sincerely apologize for", "I take full responsibility", "I assure you that this will not happen again", "I am truly sorry for any inconvenience"]'::jsonb,
 '["Don''t make excuses — own the mistake", "Don''t say ''I''m sorry but...''", "Be specific about what went wrong", "Always mention what you will do to fix it"]'::jsonb),

('status_update',
 'Project Status Update: [Project Name] — Week [Number]',
 E'Dear [Team/Manager Name],\n\nHere is the status update for [Project Name] for the week of [Date Range].\n\n**Completed This Week:**\n- [Task 1]\n- [Task 2]\n- [Task 3]\n\n**In Progress:**\n- [Task 4] — Expected completion: [Date]\n- [Task 5] — Expected completion: [Date]\n\n**Upcoming (Next Week):**\n- [Task 6]\n- [Task 7]\n\n**Blockers / Issues:**\n- [Blocker 1 — if any]\n\n**Overall Status:** [On Track / At Risk / Delayed]\n\nPlease let me know if you have any questions or need any additional information.\n\nBest regards,\n[Your Name]',
 E'ప్రియమైన [పేరు],\n\n[తేదీ] వారానికి [ప్రాజెక్ట్ పేరు] యొక్క స్టేటస్ అప్‌డేట్ ఇక్కడ ఉంది.',
 'semi_formal',
 '["Completed This Week", "In Progress", "Blockers / Issues", "Overall Status: On Track"]'::jsonb,
 '["Don''t write paragraphs — use bullet points", "Always include blockers even if it''s ''None''", "Add an overall status at the end", "Send status updates proactively, don''t wait to be asked"]'::jsonb)
ON CONFLICT DO NOTHING;

-- ─── PHONE CALL SCENARIOS ─────────────────────────────────────────────────
INSERT INTO phone_call_scenarios (title, title_telugu, category, difficulty, ai_persona, persona_voice_style, system_prompt, starter_message, key_phrases) VALUES
('Customer Support Call',
 'కస్టమర్ సపోర్ట్ కాల్',
 'customer_support', 2,
 'Neha (Customer Care Executive)',
 'professional, helpful, clear',
 'You are Neha, a customer care executive at ABC Bank. Help the customer with their query about account, transactions, or cards. Be professional, patient, and solution-oriented.',
 'Good morning! Thank you for calling ABC Bank customer care. This is Neha speaking. How may I assist you today?',
 '["How may I assist you today?", "I understand your concern", "Let me check your account details", "Your request has been noted", "Is there anything else I can help you with?"]'::jsonb),

('Job Interview Phone Screening',
 'జాబ్ ఇంటర్వ్యూ ఫోన్ స్క్రీనింగ్',
 'interview_call', 3,
 'Priya (HR - TechCorp)',
 'friendly, professional',
 'You are Priya from TechCorp HR. Conduct a 5-10 minute telephonic screening. Ask about experience, skills, current salary, expected salary, notice period, and availability for in-person interview.',
 'Hello, am I speaking with [Name]? Hi! This is Priya calling from TechCorp HR department. We received your application for the Software Engineer position. Is this a good time to talk for about 10 minutes?',
 '["Is this a good time to talk?", "Could you tell me about your current role?", "What is your notice period?", "What are your salary expectations?", "Can you come in for a face-to-face interview?"]'::jsonb),

('Doctor Appointment Booking',
 'డాక్టర్ అపాయింట్‌మెంట్ బుకింగ్',
 'appointment', 1,
 'Receptionist (City Hospital)',
 'calm, helpful',
 'You are a hospital receptionist. Help the caller book an appointment with Dr. Sharma. Ask for name, age, type of consultation, preferred date and time. Be friendly and professional.',
 'Good morning, City Hospital. How can I help you?',
 '["I would like to book an appointment", "Which doctor would you like to see?", "What is the nature of your concern?", "We have slots available on...", "Please come 10 minutes before your appointment"]'::jsonb),

('Office Internal Call',
 'ఆఫీస్ ఇంటర్నల్ కాల్',
 'office_call', 1,
 'Colleague Ramesh',
 'casual, professional',
 'You are Ramesh, a colleague. The caller needs something urgently — maybe a file, a meeting confirmation, or quick information. Be natural and helpful.',
 'Hello? Oh hi! What''s up? Do you need something?',
 '["Could you send me the report?", "Is the meeting confirmed for tomorrow?", "Can you help me with this?", "I''ll send it right away", "Let me check and call you back"]'::jsonb),

('Banking Services Call',
 'బ్యాంకింగ్ సేవల కాల్',
 'banking', 2,
 'Bank Manager Kumar',
 'formal, professional',
 'You are Kumar, a bank branch manager. Help the caller with queries about loan, FD, account opening, or net banking. Be formal and thorough.',
 'Good afternoon, State Bank of India. Branch Manager Kumar speaking. How may I help you today?',
 '["I would like to inquire about a home loan", "What documents are required?", "What is the current interest rate?", "How long does the process take?", "Could you schedule an appointment?"]'::jsonb),

('Customer Complaint Call',
 'కస్టమర్ ఫిర్యాదు కాల్',
 'customer_support', 3,
 'Customer Service Manager Asha',
 'empathetic, solution-focused',
 'You are Asha, a customer service manager. The customer has a complaint about a product or service. Listen patiently, apologize, and offer a solution. Practice handling difficult customers professionally.',
 'Thank you for calling. This is Asha, Customer Service Manager. I understand you had a concern. I am here to help. Could you please tell me what happened?',
 '["I understand your frustration", "I sincerely apologize for the inconvenience", "Let me personally ensure this is resolved", "I will escalate this to our team", "You will receive a resolution within 24 hours"]'::jsonb),

('Travel Booking Call',
 'ట్రావెల్ బుకింగ్ కాల్',
 'daily_english', 1,
 'Travel Agent Meena',
 'enthusiastic, helpful',
 'You are Meena, a travel agent. Help the caller book a train/flight/hotel. Ask for destination, dates, number of travelers, budget preference.',
 'Welcome to Meena Travels! This is Meena speaking. Where are you planning to travel? I''d love to help you plan an amazing trip!',
 '["I would like to book a ticket to", "What are the available options?", "What is the fare?", "I prefer a window seat", "Can I cancel or reschedule?"]'::jsonb)
ON CONFLICT DO NOTHING;

-- ─── GRAMMAR EXERCISES ────────────────────────────────────────────────────
INSERT INTO grammar_exercises (topic, title, title_telugu, explanation, explanation_telugu, examples, exercises, difficulty, xp_reward) VALUES
('tenses',
 'English Tenses',
 'ఇంగ్లీష్ కాలాలు',
 'Tenses tell us when an action happens — in the past, present, or future. There are 12 tenses in English, divided into 4 groups: Simple, Continuous, Perfect, and Perfect Continuous.',
 'Tenses అంటే ఒక పని ఎప్పుడు జరిగింది అని చెప్పే Grammar నియమాలు. ఇంగ్లీష్‌లో 12 tenses ఉంటాయి — Past, Present, Future అని మూడు కాలాలలో వస్తాయి.',
 '[{"english": "I eat rice every day.", "telugu": "నేను ప్రతిరోజూ అన్నం తింటాను.", "explanation": "Present Simple — habit or routine"}, {"english": "I am eating rice right now.", "telugu": "నేను ఇప్పుడు అన్నం తింటున్నాను.", "explanation": "Present Continuous — action happening now"}, {"english": "I ate rice yesterday.", "telugu": "నేను నిన్న అన్నం తిన్నాను.", "explanation": "Past Simple — completed action"}, {"english": "I have eaten rice.", "telugu": "నేను అన్నం తిన్నాను. (అనుభవం)", "explanation": "Present Perfect — past action with present relevance"}, {"english": "I will eat rice tomorrow.", "telugu": "నేను రేపు అన్నం తింటాను.", "explanation": "Future Simple — planned future action"}]'::jsonb,
 '[{"question": "She ___ to school every day.", "options": ["go", "goes", "going", "gone"], "answer": "goes", "explanation": "Present Simple uses goes for she/he/it"}, {"question": "They ___ cricket right now.", "options": ["play", "plays", "are playing", "played"], "answer": "are playing", "explanation": "Present Continuous: are + verb+ing for ongoing action"}, {"question": "I ___ the movie last night.", "options": ["watch", "watches", "watched", "have watched"], "answer": "watched", "explanation": "Past Simple for completed action with a specific past time"}, {"question": "She ___ lived here for 10 years.", "options": ["is", "was", "has", "have"], "answer": "has", "explanation": "Present Perfect: has/have + past participle"}, {"question": "We ___ go to the market tomorrow.", "options": ["will", "would", "are", "have"], "answer": "will", "explanation": "Future Simple uses will + base verb"}]'::jsonb,
 3, 20),

('articles',
 'Articles: A, An, The',
 'Articles: A, An, The',
 'Articles are small words used before nouns. "A" and "An" are indefinite articles (used for non-specific things). "The" is a definite article (used for specific things). "A" is used before consonant sounds, "An" before vowel sounds.',
 'Articles అంటే nouns ముందు వాడే చిన్న పదాలు. "A" మరియు "An" indefinite articles (నిర్దిష్టంగా లేని వస్తువుల కోసం). "The" definite article (నిర్దిష్టమైన వస్తువుల కోసం). "A" consonant sound ముందు, "An" vowel sound ముందు వస్తుంది.',
 '[{"english": "I saw a dog in the park.", "telugu": "నేను పార్క్‌లో ఒక కుక్కను చూశాను.", "explanation": "a dog — any dog, first mention; the park — specific park"}, {"english": "She is an engineer.", "telugu": "ఆమె ఒక ఇంజనీర్.", "explanation": "an engineer — vowel sound E, so use an"}, {"english": "The sun rises in the east.", "telugu": "సూర్యుడు తూర్పున ఉదయిస్తాడు.", "explanation": "the sun — only one sun, unique things use the"}, {"english": "I need a pen and an umbrella.", "telugu": "నాకు ఒక పెన్నూ మరియు గొడుగూ కావాలి.", "explanation": "a pen (consonant P), an umbrella (vowel U)"}]'::jsonb,
 '[{"question": "She is ___ honest person.", "options": ["a", "an", "the", "no article"], "answer": "an", "explanation": "honest starts with vowel sound /ɒ/, so use an"}, {"question": "I live near ___ Eiffel Tower.", "options": ["a", "an", "the", "no article"], "answer": "the", "explanation": "Famous unique landmarks use the"}, {"question": "He wants to become ___ doctor.", "options": ["a", "an", "the", "no article"], "answer": "a", "explanation": "doctor starts with consonant d, so use a"}, {"question": "___ gold is a precious metal.", "options": ["A", "An", "The", "No article"], "answer": "No article", "explanation": "General substances/materials don''t use articles"}, {"question": "I read ___ book you recommended.", "options": ["a", "an", "the", "no article"], "answer": "the", "explanation": "specific book already known to both speakers — use the"}]'::jsonb,
 2, 15),

('prepositions',
 'Prepositions: In, On, At and More',
 'Prepositions: In, On, At మరియు ఇతరాలు',
 'Prepositions show the relationship between a noun/pronoun and other words in a sentence. Common prepositions: in (inside), on (surface/day), at (specific place/time), for (duration/purpose), with (accompaniment), to (direction), from (origin).',
 'Prepositions అంటే noun లేదా pronoun మరియు వాక్యంలోని ఇతర పదాల మధ్య సంబంధాన్ని చూపించే పదాలు. In (లోపల), On (పై), At (నిర్దిష్ట స్థలం/సమయం) అనేవి అత్యంత సాధారణమైనవి.',
 '[{"english": "I live in Hyderabad.", "telugu": "నేను హైదరాబాద్‌లో నివసిస్తున్నాను.", "explanation": "in — for cities, countries, enclosed spaces"}, {"english": "The book is on the table.", "telugu": "పుస్తకం టేబుల్ పై ఉంది.", "explanation": "on — for surfaces"}, {"english": "I will meet you at 5 PM.", "telugu": "నేను మిమ్మల్ని సాయంత్రం 5 గంటలకు కలుస్తాను.", "explanation": "at — for specific times and places"}, {"english": "She works for Google.", "telugu": "ఆమె Google కోసం పని చేస్తుంది.", "explanation": "for — showing purpose or employer"}]'::jsonb,
 '[{"question": "She arrived ___ Monday morning.", "options": ["in", "on", "at", "for"], "answer": "on", "explanation": "on — used for days of the week"}, {"question": "I will call you ___ 6 PM.", "options": ["in", "on", "at", "by"], "answer": "at", "explanation": "at — used for specific clock times"}, {"question": "He studied ___ three hours.", "options": ["in", "on", "at", "for"], "answer": "for", "explanation": "for — used for duration of time"}, {"question": "The keys are ___ the bag.", "options": ["in", "on", "at", "into"], "answer": "in", "explanation": "in — used for items inside an enclosed container"}, {"question": "I will finish ___ Friday.", "options": ["in", "on", "at", "by"], "answer": "by", "explanation": "by — means no later than that time/date"}]'::jsonb,
 2, 15),

('active_passive',
 'Active and Passive Voice',
 'Active మరియు Passive Voice',
 'In Active Voice, the subject performs the action. In Passive Voice, the subject receives the action. Passive is formed with: be (am/is/are/was/were) + past participle. Use passive when the doer is unknown, unimportant, or obvious.',
 'Active Voice లో subject పని చేస్తుంది. Passive Voice లో subject పని అందుకుంటుంది. Passive Voice: be (am/is/are/was/were) + past participle తో తయారవుతుంది. పని చేసిన వ్యక్తి తెలియనప్పుడు లేదా అనవసరమైనప్పుడు Passive ఉపయోగిస్తాం.',
 '[{"english": "Active: The chef cooks the food.", "telugu": "Active: వంటవాడు ఆహారం వండుతాడు.", "explanation": "Subject (chef) does the action"}, {"english": "Passive: The food is cooked by the chef.", "telugu": "Passive: ఆహారం వంటవాడిచే వండబడుతుంది.", "explanation": "Subject (food) receives the action"}, {"english": "Active: They built this bridge in 1990.", "telugu": "Active: వారు ఈ వంతెనను 1990లో నిర్మించారు.", "explanation": "Active — doer is known"}, {"english": "Passive: This bridge was built in 1990.", "telugu": "Passive: ఈ వంతెన 1990లో నిర్మించబడింది.", "explanation": "Passive — doer not important"}]'::jsonb,
 '[{"question": "The cake ___ by Mary. (bake)", "options": ["baked", "was baked", "is baking", "bakes"], "answer": "was baked", "explanation": "Past passive: was + past participle (baked)"}, {"question": "This letter ___ in 1850. (write)", "options": ["wrote", "writes", "was written", "is written"], "answer": "was written", "explanation": "Past passive for historical fact: was written"}, {"question": "The new policy ___ tomorrow. (announce)", "options": ["will announce", "will be announced", "announces", "is announcing"], "answer": "will be announced", "explanation": "Future passive: will be + past participle"}, {"question": "English ___ all over the world. (speak)", "options": ["spoken", "speaks", "is spoken", "spoke"], "answer": "is spoken", "explanation": "Present passive for general truths: is + past participle"}, {"question": "The documents ___ by the manager. (sign)", "options": ["signed", "have signed", "have been signed", "is signed"], "answer": "have been signed", "explanation": "Present perfect passive: have/has been + past participle"}]'::jsonb,
 3, 20),

('sentence_structure',
 'Sentence Structure',
 'వాక్య నిర్మాణం',
 'A sentence needs a Subject and a Verb to be complete. Basic structure: Subject + Verb + Object (SVO). Types: Simple (1 clause), Compound (2 clauses with and/but/or), Complex (main + subordinate clause with because/when/if/although).',
 'ఒక వాక్యానికి Subject మరియు Verb తప్పనిసరిగా ఉండాలి. మూల నిర్మాణం: Subject + Verb + Object (SVO). రకాలు: Simple (1 clause), Compound (2 clauses), Complex (main + subordinate clause).',
 '[{"english": "Ram plays cricket. (Simple)", "telugu": "రాం క్రికెట్ ఆడతాడు.", "explanation": "Simple sentence — one subject, one verb"}, {"english": "I was tired, but I finished the work. (Compound)", "telugu": "నేను అలసిపోయాను, కానీ పని పూర్తి చేశాను.", "explanation": "Compound — two independent clauses joined by but"}, {"english": "I stayed home because it was raining. (Complex)", "telugu": "వర్షం పడుతోంది కాబట్టి నేను ఇంటిలో ఉన్నాను.", "explanation": "Complex — main clause + subordinate clause with because"}]'::jsonb,
 '[{"question": "Which is a complete sentence?", "options": ["Running fast.", "She runs fast.", "Fast running girl.", "In the morning."], "answer": "She runs fast.", "explanation": "A complete sentence needs subject (She) + verb (runs)"}, {"question": "''I like tea ___ my friend prefers coffee.''", "options": ["because", "but", "although", "since"], "answer": "but", "explanation": "but joins two contrasting independent clauses"}, {"question": "''I will call you ___ I reach home.''", "options": ["and", "but", "when", "so"], "answer": "when", "explanation": "when introduces a time-based subordinate clause"}, {"question": "Identify the subject: ''The tall boy won the race.''", "options": ["tall", "boy", "The tall boy", "race"], "answer": "The tall boy", "explanation": "The complete subject includes all words that describe who/what"}, {"question": "''Although it rained, ___''", "options": ["but we went", "we went to the park", "and we stayed", "so we came"], "answer": "we went to the park", "explanation": "Although starts a subordinate clause — needs an independent main clause to complete"}]'::jsonb,
 3, 20),

('reported_speech',
 'Reported Speech (Indirect Speech)',
 'Reported Speech (Indirect Speech)',
 'Reported Speech is when we tell someone what another person said, without using their exact words. Direct: He said, "I am hungry." → Reported: He said that he was hungry. Tenses usually shift back (present → past) in reported speech.',
 'Reported Speech అంటే మరొక వ్యక్తి చెప్పింది మనం చెప్పేటప్పుడు exact words వాడకుండా చెప్పడం. Tenses సాధారణంగా ఒక step వెనక్కి వెళ్తాయి.',
 '[{"english": "Direct: She said, ''I am tired.'' → Reported: She said that she was tired.", "telugu": "Direct: ''నాకు అలసట గా ఉంది'' → Reported: ఆమె అలసిపోయిందని చెప్పింది.", "explanation": "am → was (present to past shift)"}, {"english": "Direct: He said, ''I will come.'' → Reported: He said that he would come.", "telugu": "Direct: ''నేను వస్తాను'' → Reported: అతను వస్తాడని చెప్పాడు.", "explanation": "will → would"}, {"english": "Direct: She asked, ''Are you coming?'' → Reported: She asked if I was coming.", "telugu": "Direct: ''మీరు వస్తున్నారా?'' → Reported: నేను వస్తున్నానా అని అడిగింది.", "explanation": "Questions use if/whether in reported speech"}]'::jsonb,
 '[{"question": "''I eat rice.'' → He said that he ___ rice.", "options": ["eat", "eats", "ate", "eaten"], "answer": "ate", "explanation": "Present simple (eat) → Past simple (ate) in reported speech"}, {"question": "''I am working.'' → She said she ___ working.", "options": ["is", "was", "were", "has been"], "answer": "was", "explanation": "Present continuous (am working) → Past continuous (was working)"}, {"question": "''I will help you.'' → He said he ___ help me.", "options": ["will", "would", "shall", "could"], "answer": "would", "explanation": "will → would in reported speech"}, {"question": "''Do you like cricket?'' → She asked ___ I liked cricket.", "options": ["that", "if", "what", "which"], "answer": "if", "explanation": "Yes/No questions use if or whether in reported speech"}, {"question": "''Don''t make noise.'' → He told me ___ make noise.", "options": ["don''t", "not to", "to not", "no to"], "answer": "not to", "explanation": "Negative imperatives become: told + not to + verb"}]'::jsonb,
 4, 25),

('verbs',
 'Regular and Irregular Verbs',
 'Regular మరియు Irregular Verbs',
 'Regular verbs form past tense by adding -ed (walk → walked). Irregular verbs have unique past forms that must be memorized (go → went, eat → ate, take → took). Most common verbs in English are irregular.',
 'Regular verbs కి past tense చేయడానికి -ed చేర్చాలి (walk → walked). Irregular verbs కి వేరే forms ఉంటాయి — వాటిని గుర్తుపెట్టుకోవాలి (go → went, eat → ate, give → gave).',
 '[{"english": "Regular: I walked to school.", "telugu": "నేను పాఠశాలకు నడిచాను.", "explanation": "walk → walked (regular: +ed)"}, {"english": "Irregular: I went to school.", "telugu": "నేను పాఠశాలకు వెళ్ళాను.", "explanation": "go → went (irregular: completely different form)"}, {"english": "Irregular: She took the bus.", "telugu": "ఆమె బస్సు ఎక్కింది.", "explanation": "take → took (irregular)"}, {"english": "Regular: They finished the project.", "telugu": "వారు ప్రాజెక్ట్ పూర్తి చేశారు.", "explanation": "finish → finished (regular: +ed)"}]'::jsonb,
 '[{"question": "Past tense of ''write'':", "options": ["writed", "wrote", "written", "writes"], "answer": "wrote", "explanation": "write is irregular: write → wrote → written"}, {"question": "Past tense of ''play'':", "options": ["plaied", "played", "playing", "plaid"], "answer": "played", "explanation": "play is regular: play → played (+ed)"}, {"question": "Past tense of ''buy'':", "options": ["buyed", "boughted", "bought", "buyed"], "answer": "bought", "explanation": "buy is irregular: buy → bought"}, {"question": "Past tense of ''jump'':", "options": ["jumpt", "jumped", "jumt", "jumping"], "answer": "jumped", "explanation": "jump is regular: jump → jumped (+ed)"}, {"question": "Past tense of ''speak'':", "options": ["speaked", "spoke", "spoken", "speaks"], "answer": "spoke", "explanation": "speak is irregular: speak → spoke → spoken"}]'::jsonb,
 2, 15)
ON CONFLICT DO NOTHING;
